/**
 * VIP Plans - single source of truth.
 *
 * Financial model:
 *   dailyProfit * durationDays = netProfit
 *   totalReturn = price + netProfit
 *   monthlyPct  = (netProfit / price) * 100
 */

const VIP_LEVELS = [
  {
    level:        0,
    name:         'التدريب',
    nameEn:       'Training',
    tier:         'مبتدئ',
    price:        0,
    monthlyPct:   0,
    dailyProfit:  0.10,
    dailyBonus:   0,
    dailyTotal:   0.10,
    durationDays: 5,
    totalReturn:  0.50,
    isTraining:   true,
    badge:        null,
    description:  'خطة مجانية مخصصة لتجربة النظام والتعرف على طريقة عمل المنصة قبل البدء في الخطط المدفوعة.',
    marketing:    'خطة مجانية مخصصة لتجربة النظام والتعرف على طريقة عمل المنصة قبل البدء في الخطط المدفوعة.',
    planLevel:    'مبتدئ',
    followType:   'تجربة النظام',
    planStatus:   'تفعيل فوري',
    activationText: 'فوري بعد التسجيل',
    detailBullets: [
      'مدة الاشتراك: 5 أيام',
      'إجمالي العائد: $0.50',
      'التفعيل: فوري بعد التسجيل',
    ],
  },
  {
    level:        1,
    name:         'البرونزي',
    nameEn:       'Bronze',
    tier:         'مستوى مبتدئ',
    planLevel:    'مستوى مبتدئ',
    followType:   'متابعة يومية',
    planStatus:   'نمو مستمر',
    subscribers:  { base: 216, min: 216, max: 216 },
    demandRate:   68,
    price:        10,
    monthlyPct:   105,
    dailyProfit:  0.35,
    dailyBonus:   0,
    dailyTotal:   0.35,
    durationDays: 30,
    totalReturn:  20.50,
    get netProfit() { return +(this.totalReturn - this.price).toFixed(2); },
    badge:        null,
    description:  'خطة مناسبة للمستخدمين الجدد الذين يريدون بداية مستقرة داخل المنصة مع متابعة يومية للأرباح وإضافة تلقائية للرصيد.',
    marketing:    'مناسب لبداية بناء دخل إضافي تدريجي مع تجربة استثمار بسيطة وسهلة المتابعة.',
    suitableFor:  'مناسب لبداية بناء دخل إضافي تدريجي مع تجربة استثمار بسيطة وسهلة المتابعة.',
    activationText: 'فوري بعد تأكيد الإيداع',
    detailBullets: [
      'يتم تحديث الأرباح بشكل دوري داخل الحساب.',
      'الأرباح تضاف تدريجياً حسب نشاط الخطة.',
      'التفعيل فوري بعد تأكيد الإيداع.',
      'الأرباح تختلف حسب مدة النشاط وحالة الخطة داخل المنصة.',
    ],
  },
  {
    level:        2,
    name:         'الفضي',
    nameEn:       'Silver',
    tier:         'مستوى متقدم',
    planLevel:    'مستوى متقدم',
    followType:   'متابعة منتظمة',
    planStatus:   'نمو مستمر',
    subscribers:  { base: 288, min: 288, max: 288 },
    demandRate:   82,
    price:        30,
    monthlyPct:   110,
    dailyProfit:  1.10,
    dailyBonus:   0,
    dailyTotal:   1.10,
    durationDays: 30,
    totalReturn:  63.00,
    get netProfit() { return +(this.totalReturn - this.price).toFixed(2); },
    badge:        'الأكثر اختياراً',
    description:  'خطة متقدمة تمنح متابعة أفضل للأرباح اليومية مع استقرار أكبر للمستخدمين النشيطين داخل المنصة.',
    marketing:    'خيار جيد للمستخدمين الذين يريدون تحسين دخلهم الشهري بشكل تدريجي مع متابعة منتظمة للأرباح.',
    suitableFor:  'خيار جيد للمستخدمين الذين يريدون تحسين دخلهم الشهري بشكل تدريجي مع متابعة منتظمة للأرباح.',
    activationText: 'فوري بعد تأكيد الإيداع',
    detailBullets: [
      'الأرباح تضاف تلقائياً إلى الحساب.',
      'تحديث الرصيد يتم بشكل منتظم.',
      'متابعة يومية لنشاط الخطة.',
      'الأرباح تختلف حسب نشاط الحساب ومدة الخطة.',
    ],
  },
  {
    level:        3,
    name:         'الذهبي',
    nameEn:       'Gold',
    tier:         'مستوى احترافي',
    planLevel:    'مستوى احترافي',
    followType:   'متابعة متقدمة',
    planStatus:   'نشطة ومستقرة',
    subscribers:  { base: 174, min: 174, max: 174 },
    demandRate:   86,
    price:        50,
    monthlyPct:   120,
    dailyProfit:  2.00,
    dailyBonus:   0,
    dailyTotal:   2.00,
    durationDays: 30,
    totalReturn:  110.00,
    get netProfit() { return +(this.totalReturn - this.price).toFixed(2); },
    badge:        null,
    description:  'خطة احترافية مخصصة للمستخدمين الذين يريدون أرباحاً أفضل مع استقرار أكبر وتحديث مستمر للحساب داخل المنصة.',
    marketing:    'خطة احترافية مخصصة للمستخدمين الذين يريدون أرباحاً أفضل مع استقرار أكبر وتحديث مستمر للحساب داخل المنصة.',
    suitableFor:  'خطة احترافية مخصصة للمستخدمين الذين يريدون أرباحاً أفضل مع استقرار أكبر وتحديث مستمر للحساب داخل المنصة.',
    activationText: 'فوري بعد تأكيد الإيداع',
    detailBullets: [
      'الأرباح تضاف تلقائياً إلى الحساب.',
      'تحديث الرصيد يتم بشكل منتظم.',
      'متابعة يومية لنشاط الخطة.',
      'الأرباح تختلف حسب نشاط الحساب وحركة السوق.',
      'استقرار أفضل للمستخدمين النشيطين.',
    ],
  },
  {
    level:        4,
    name:         'البلاتيني',
    nameEn:       'Platinum',
    tier:         'مستوى متقدم جداً',
    planLevel:    'مستوى متقدم جداً',
    followType:   'متابعة متقدمة جداً',
    planStatus:   'نشطة ومستقرة',
    subscribers:  { base: 126, min: 126, max: 126 },
    demandRate:   79,
    price:        200,
    monthlyPct:   95,
    dailyProfit:  6.33,
    dailyBonus:   0,
    dailyTotal:   6.33,
    durationDays: 30,
    totalReturn:  390.00,
    get netProfit() { return +(this.totalReturn - this.price).toFixed(2); },
    badge:        null,
    description:  'خطة قوية مخصصة للمستخدمين الذين يريدون مستوى أعلى من الأرباح مع متابعة متقدمة وتحديث مستمر لنشاط الحساب داخل المنصة.',
    marketing:    'خطة قوية مخصصة للمستخدمين الذين يريدون مستوى أعلى من الأرباح مع متابعة متقدمة وتحديث مستمر لنشاط الحساب داخل المنصة.',
    suitableFor:  'خطة قوية مخصصة للمستخدمين الذين يريدون مستوى أعلى من الأرباح مع متابعة متقدمة وتحديث مستمر لنشاط الحساب داخل المنصة.',
    activationText: 'فوري بعد تأكيد الإيداع',
    detailBullets: [
      'الأرباح تضاف تلقائياً إلى الحساب.',
      'تحديث الرصيد يتم بشكل منتظم.',
      'متابعة يومية متقدمة لنشاط الخطة.',
      'الأرباح تختلف حسب نشاط الحساب وحركة السوق.',
      'استقرار أعلى للمستخدمين النشيطين.',
    ],
  },
  {
    level:        5,
    name:         'الماسي',
    nameEn:       'Diamond',
    tier:         'مستوى VIP',
    planLevel:    'مستوى VIP',
    followType:   'متابعة VIP',
    planStatus:   'نمو مستمر',
    subscribers:  { base: 92, min: 92, max: 92 },
    demandRate:   74,
    price:        300,
    monthlyPct:   140,
    dailyProfit:  14.00,
    dailyBonus:   0,
    dailyTotal:   14.00,
    durationDays: 30,
    totalReturn:  720.00,
    get netProfit() { return +(this.totalReturn - this.price).toFixed(2); },
    badge:        'VIP',
    description:  'مستوى VIP مخصص للمستخدمين الأكثر نشاطاً، مع تجربة احترافية وتحديثات مستمرة للأرباح داخل الحساب.',
    marketing:    'مناسب لبناء دخل إضافي شهري قوي مع متابعة احترافية وإدارة أفضل للحساب داخل النظام.',
    suitableFor:  'مناسب لبناء دخل إضافي شهري قوي مع متابعة احترافية وإدارة أفضل للحساب داخل النظام.',
    activationText: 'فوري بعد تأكيد الإيداع',
    detailBullets: [
      'الأرباح تضاف تلقائياً إلى الرصيد.',
      'تحديثات مباشرة حسب نشاط الحساب.',
      'متابعة أسرع وإدارة أفضل للخطة.',
      'الأرباح تضاف تدريجياً حسب نشاط الخطة وحالة الحساب.',
    ],
  },
];

const REFERRAL_RATES = {
  L1: parseFloat(process.env.REFERRAL_L1 || 15),
  L2: parseFloat(process.env.REFERRAL_L2 || 10),
  L3: parseFloat(process.env.REFERRAL_L3 || 5),
};

const PAYMENT_METHODS = [
  { id: 'TRC20',   name: 'USDT (TRC20)',   currency: 'USDT', icon: '₮' },
  { id: 'BEP20',   name: 'USDT (BEP20)',   currency: 'USDT', icon: '💎' },
  { id: 'POLYGON', name: 'USDT (POLYGON)', currency: 'USDT', icon: '💜' },
];

const PLATFORM_WALLETS = {
  TRC20:   process.env.WALLET_USDT_TRC20   || 'TRX_ADDRESS_HERE',
  BEP20:   process.env.WALLET_USDT_BEP20   || 'BEP_ADDRESS_HERE',
  POLYGON: process.env.WALLET_USDT_POLYGON || 'POLYGON_ADDRESS_HERE',
};

module.exports = { VIP_LEVELS, PAYMENT_METHODS, PLATFORM_WALLETS, REFERRAL_RATES };
